"""empty message

Revision ID: 16897bc3be7
Revises: 3fbec43f99d
Create Date: 2015-02-06 22:55:05.117653

"""

# revision identifiers, used by Alembic.
revision = '16897bc3be7'
down_revision = '3fbec43f99d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('truncated_content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastes', 'truncated_content')
    ### end Alembic commands ###
