"""empty message

Revision ID: 3fbec43f99d
Revises: 36696b7e8bd
Create Date: 2015-02-04 19:47:51.389497

"""

# revision identifiers, used by Alembic.
revision = '3fbec43f99d'
down_revision = '36696b7e8bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
